import { Model } from "@nozbe/watermelondb";
import { field, relation, text } from "@nozbe/watermelondb/decorators";
import type PyrolysisSession from "./PyrolysisSession";

export default class PyrolysisBatch extends Model {
  static table = "pyrolysis_batches";
  static associations = {
    pyrolysis_sessions: { type: "belongs_to" as const, key: "session_id" },
  };

  @relation("pyrolysis_sessions", "session_id") session!: PyrolysisSession;
  @text("session_id") sessionId!: string;
  @text("server_id") serverId!: string | null;
  @text("kontikki_id") kontikkiId!: string;
  @text("kontikki_code") kontikkiCode!: string;
  @text("producer_name") producerName!: string | null;
  @text("batch_number") batchNumber!: string | null;
  @field("feedstock_quantity") feedstockQuantity!: number | null;
  @text("farm_id") farmId!: string | null;
  @text("farm_name") farmName!: string | null;
  @field("avg_feedstock_size_cm") avgFeedstockSizeCm!: number | null;
  @text("feedstock_id") feedstockId!: string | null;
  @text("feedstock_name") feedstockName!: string | null;
  @field("location_lat") locationLat!: number | null;
  @field("location_lng") locationLng!: number | null;
  @text("location_address") locationAddress!: string | null;
  @text("feedstock_photo_local_uri") feedstockPhotoLocalUri!: string | null;
  @text("feedstock_photo_url") feedstockPhotoUrl!: string | null;
  @text("feedstock_size_photo_local_uri") feedstockSizePhotoLocalUri!: string | null;
  @text("feedstock_size_photo_url") feedstockSizePhotoUrl!: string | null;
  @text("feedstock_photo_metadata_json") feedstockPhotoMetadataJson!: string | null;
  @text("feedstock_size_photo_metadata_json") feedstockSizePhotoMetadataJson!: string | null;
  @field("moisture_reading_1") moistureReading1!: number | null;
  @field("moisture_reading_2") moistureReading2!: number | null;
  @field("moisture_reading_3") moistureReading3!: number | null;
  @field("moisture_reading_4") moistureReading4!: number | null;
  @field("moisture_reading_5") moistureReading5!: number | null;
  @text("moisture_photo_local_uri_1") moisturePhotoLocalUri1!: string | null;
  @text("moisture_photo_local_uri_2") moisturePhotoLocalUri2!: string | null;
  @text("moisture_photo_local_uri_3") moisturePhotoLocalUri3!: string | null;
  @text("moisture_photo_local_uri_4") moisturePhotoLocalUri4!: string | null;
  @text("moisture_photo_local_uri_5") moisturePhotoLocalUri5!: string | null;
  @text("moisture_photo_url_1") moisturePhotoUrl1!: string | null;
  @text("moisture_photo_url_2") moisturePhotoUrl2!: string | null;
  @text("moisture_photo_url_3") moisturePhotoUrl3!: string | null;
  @text("moisture_photo_url_4") moisturePhotoUrl4!: string | null;
  @text("moisture_photo_url_5") moisturePhotoUrl5!: string | null;
  @text("moisture_photo_metadata_json_1") moisturePhotoMetadataJson1!: string | null;
  @text("moisture_photo_metadata_json_2") moisturePhotoMetadataJson2!: string | null;
  @text("moisture_photo_metadata_json_3") moisturePhotoMetadataJson3!: string | null;
  @text("moisture_photo_metadata_json_4") moisturePhotoMetadataJson4!: string | null;
  @text("moisture_photo_metadata_json_5") moisturePhotoMetadataJson5!: string | null;
  @text("stage_initial_photo_local_uri") stageInitialPhotoLocalUri!: string | null;
  @text("stage_middle_photo_local_uri") stageMiddlePhotoLocalUri!: string | null;
  @text("stage_final_photo_local_uri") stageFinalPhotoLocalUri!: string | null;
  @text("stage_quenching_photo_local_uri") stageQuenchingPhotoLocalUri!: string | null;
  @text("stage_initial_photo_url") stageInitialPhotoUrl!: string | null;
  @text("stage_middle_photo_url") stageMiddlePhotoUrl!: string | null;
  @text("stage_final_photo_url") stageFinalPhotoUrl!: string | null;
  @text("stage_quenching_photo_url") stageQuenchingPhotoUrl!: string | null;
  @text("stage_initial_captured_at") stageInitialCapturedAt!: string | null;
  @text("stage_middle_captured_at") stageMiddleCapturedAt!: string | null;
  @text("stage_final_captured_at") stageFinalCapturedAt!: string | null;
  @text("stage_quenching_captured_at") stageQuenchingCapturedAt!: string | null;
  @text("stage_initial_saved_at") stageInitialSavedAt!: string | null;
  @text("stage_middle_saved_at") stageMiddleSavedAt!: string | null;
  @text("stage_final_saved_at") stageFinalSavedAt!: string | null;
  @text("stage_quenching_saved_at") stageQuenchingSavedAt!: string | null;
  @text("stage_initial_photo_metadata_json") stageInitialPhotoMetadataJson!: string | null;
  @text("stage_middle_photo_metadata_json") stageMiddlePhotoMetadataJson!: string | null;
  @text("stage_final_photo_metadata_json") stageFinalPhotoMetadataJson!: string | null;
  @text("stage_quenching_photo_metadata_json") stageQuenchingPhotoMetadataJson!: string | null;
  @field("info_completed") infoCompleted!: boolean;
  @field("moisture_completed") moistureCompleted!: boolean;
  @field("pyrolysis_completed") pyrolysisCompleted!: boolean;
  @text("info_saved_at") infoSavedAt!: string | null;
  @text("moisture_saved_at") moistureSavedAt!: string | null;
  @text("pyrolysis_saved_at") pyrolysisSavedAt!: string | null;
  @text("yield_saved_at") yieldSavedAt!: string | null;
  @field("yield_percent") yieldPercent!: number | null;
  @text("comment") comment!: string | null;
  @text("sample_id") sampleId!: string | null;
  @text("sample_photo_local_uri") samplePhotoLocalUri!: string | null;
  @text("sample_photo_url") samplePhotoUrl!: string | null;
  @text("sample_photo_metadata_json") samplePhotoMetadataJson!: string | null;
  @text("sample_saved_at") sampleSavedAt!: string | null;
  @field("sample_completed") sampleCompleted!: boolean;
  @text("sync_status") uploadStatus!: string;
  @text("sync_error") syncError!: string | null;
  @field("created_at") createdAt!: number;
  @field("updated_at") updatedAt!: number;
}
