import { appSchema, tableSchema } from "@nozbe/watermelondb";

const flatBatchColumns = [
  { name: "session_id", type: "string", isIndexed: true },
  { name: "server_id", type: "string", isOptional: true },
  { name: "kontikki_id", type: "string", isIndexed: true },
  { name: "kontikki_code", type: "string" },
  { name: "producer_name", type: "string", isOptional: true },
  { name: "batch_number", type: "string", isOptional: true },
  { name: "feedstock_quantity", type: "number", isOptional: true },
  { name: "farm_id", type: "string", isOptional: true },
  { name: "farm_name", type: "string", isOptional: true },
  { name: "avg_feedstock_size_cm", type: "number", isOptional: true },
  { name: "feedstock_id", type: "string", isOptional: true },
  { name: "feedstock_name", type: "string", isOptional: true },
  { name: "location_lat", type: "number", isOptional: true },
  { name: "location_lng", type: "number", isOptional: true },
  { name: "location_address", type: "string", isOptional: true },
  { name: "feedstock_photo_local_uri", type: "string", isOptional: true },
  { name: "feedstock_photo_url", type: "string", isOptional: true },
  { name: "feedstock_size_photo_local_uri", type: "string", isOptional: true },
  { name: "feedstock_size_photo_url", type: "string", isOptional: true },
  { name: "feedstock_photo_metadata_json", type: "string", isOptional: true },
  { name: "feedstock_size_photo_metadata_json", type: "string", isOptional: true },
  { name: "moisture_reading_1", type: "number", isOptional: true },
  { name: "moisture_reading_2", type: "number", isOptional: true },
  { name: "moisture_reading_3", type: "number", isOptional: true },
  { name: "moisture_reading_4", type: "number", isOptional: true },
  { name: "moisture_reading_5", type: "number", isOptional: true },
  { name: "moisture_photo_local_uri_1", type: "string", isOptional: true },
  { name: "moisture_photo_local_uri_2", type: "string", isOptional: true },
  { name: "moisture_photo_local_uri_3", type: "string", isOptional: true },
  { name: "moisture_photo_local_uri_4", type: "string", isOptional: true },
  { name: "moisture_photo_local_uri_5", type: "string", isOptional: true },
  { name: "moisture_photo_url_1", type: "string", isOptional: true },
  { name: "moisture_photo_url_2", type: "string", isOptional: true },
  { name: "moisture_photo_url_3", type: "string", isOptional: true },
  { name: "moisture_photo_url_4", type: "string", isOptional: true },
  { name: "moisture_photo_url_5", type: "string", isOptional: true },
  { name: "moisture_photo_metadata_json_1", type: "string", isOptional: true },
  { name: "moisture_photo_metadata_json_2", type: "string", isOptional: true },
  { name: "moisture_photo_metadata_json_3", type: "string", isOptional: true },
  { name: "moisture_photo_metadata_json_4", type: "string", isOptional: true },
  { name: "moisture_photo_metadata_json_5", type: "string", isOptional: true },
  { name: "stage_initial_photo_local_uri", type: "string", isOptional: true },
  { name: "stage_middle_photo_local_uri", type: "string", isOptional: true },
  { name: "stage_final_photo_local_uri", type: "string", isOptional: true },
  { name: "stage_quenching_photo_local_uri", type: "string", isOptional: true },
  { name: "stage_initial_photo_url", type: "string", isOptional: true },
  { name: "stage_middle_photo_url", type: "string", isOptional: true },
  { name: "stage_final_photo_url", type: "string", isOptional: true },
  { name: "stage_quenching_photo_url", type: "string", isOptional: true },
  { name: "stage_initial_captured_at", type: "string", isOptional: true },
  { name: "stage_middle_captured_at", type: "string", isOptional: true },
  { name: "stage_final_captured_at", type: "string", isOptional: true },
  { name: "stage_quenching_captured_at", type: "string", isOptional: true },
  { name: "stage_initial_saved_at", type: "string", isOptional: true },
  { name: "stage_middle_saved_at", type: "string", isOptional: true },
  { name: "stage_final_saved_at", type: "string", isOptional: true },
  { name: "stage_quenching_saved_at", type: "string", isOptional: true },
  { name: "stage_initial_photo_metadata_json", type: "string", isOptional: true },
  { name: "stage_middle_photo_metadata_json", type: "string", isOptional: true },
  { name: "stage_final_photo_metadata_json", type: "string", isOptional: true },
  { name: "stage_quenching_photo_metadata_json", type: "string", isOptional: true },
  { name: "info_completed", type: "boolean" },
  { name: "moisture_completed", type: "boolean" },
  { name: "pyrolysis_completed", type: "boolean" },
  { name: "info_saved_at", type: "string", isOptional: true },
  { name: "moisture_saved_at", type: "string", isOptional: true },
  { name: "pyrolysis_saved_at", type: "string", isOptional: true },
  { name: "yield_saved_at", type: "string", isOptional: true },
  { name: "yield_percent", type: "number", isOptional: true },
  { name: "comment", type: "string", isOptional: true },
  { name: "sample_id", type: "string", isOptional: true },
  { name: "sample_photo_local_uri", type: "string", isOptional: true },
  { name: "sample_photo_url", type: "string", isOptional: true },
  { name: "sample_photo_metadata_json", type: "string", isOptional: true },
  { name: "sample_saved_at", type: "string", isOptional: true },
  { name: "sample_completed", type: "boolean" },
  { name: "sync_status", type: "string" },
  { name: "sync_error", type: "string", isOptional: true },
  { name: "created_at", type: "number" },
  { name: "updated_at", type: "number" },
] as const;

export default appSchema({
  version: 10,
  tables: [
    tableSchema({
      name: "farmers",
      columns: [
        { name: "server_id", type: "string", isOptional: true },
        { name: "farmer_name", type: "string" },
        { name: "mobile_number", type: "string" },
        { name: "latitude", type: "number" },
        { name: "longitude", type: "number" },
        { name: "address", type: "string" },
        { name: "total_land_size", type: "number" },
        { name: "crops", type: "string" },
        { name: "interested_in_biochar", type: "boolean" },
        { name: "prior_biochar_exp", type: "boolean" },
        { name: "prior_biochar_acreage", type: "number", isOptional: true },
        { name: "consent_document_url", type: "string", isOptional: true },
        { name: "consent_local_uri", type: "string", isOptional: true },
        { name: "estimated_biomass", type: "number" },
        { name: "created_by", type: "string" },
        { name: "assigned_to", type: "string" },
        { name: "sync_status", type: "string" },
        { name: "sync_error", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "sync_queue",
      columns: [
        { name: "entity_type", type: "string" },
        { name: "entity_local_id", type: "string" },
        { name: "operation", type: "string" },
        { name: "status", type: "string" },
        { name: "retries", type: "number" },
        { name: "error_message", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "pyrolysis_sessions",
      columns: [
        { name: "server_id", type: "string", isOptional: true },
        { name: "operator_id", type: "string" },
        { name: "status", type: "string" },
        { name: "current_step", type: "string" },
        { name: "sync_status", type: "string" },
        { name: "sync_error", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "pyrolysis_batches",
      columns: [...flatBatchColumns],
    }),
    tableSchema({
      name: "mixing_entries",
      columns: [
        { name: "server_id", type: "string", isOptional: true },
        { name: "operator_id", type: "string", isIndexed: true },
        { name: "started_at", type: "string" },
        { name: "status", type: "string" },
        { name: "farm_id", type: "string", isOptional: true },
        { name: "farm_name", type: "string", isOptional: true },
        { name: "location_lat", type: "number", isOptional: true },
        { name: "location_lng", type: "number", isOptional: true },
        { name: "location_address", type: "string", isOptional: true },
        { name: "material_type", type: "string", isOptional: true },
        { name: "material_to_biochar_ratio", type: "number", isOptional: true },
        { name: "comment", type: "string", isOptional: true },
        { name: "biochar_photo_local_uri", type: "string", isOptional: true },
        { name: "biochar_photo_url", type: "string", isOptional: true },
        { name: "biochar_photo_metadata_json", type: "string", isOptional: true },
        { name: "substrate_photo_local_uri", type: "string", isOptional: true },
        { name: "substrate_photo_url", type: "string", isOptional: true },
        { name: "substrate_photo_metadata_json", type: "string", isOptional: true },
        { name: "mixing_photo_local_uri", type: "string", isOptional: true },
        { name: "mixing_photo_url", type: "string", isOptional: true },
        { name: "mixing_photo_metadata_json", type: "string", isOptional: true },
        { name: "sync_status", type: "string" },
        { name: "sync_error", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "mixing_pyrolysis_links",
      columns: [
        { name: "mixing_entry_id", type: "string", isIndexed: true },
        { name: "pyrolysis_batch_server_id", type: "string", isIndexed: true },
        { name: "pyrolysis_batch_local_id", type: "string", isOptional: true },
        { name: "kontikki_code", type: "string", isOptional: true },
        { name: "batch_number", type: "string", isOptional: true },
        { name: "producer_name", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: "application_entries",
      columns: [
        { name: "server_id", type: "string", isOptional: true },
        { name: "operator_id", type: "string", isIndexed: true },
        { name: "applied_at", type: "string" },
        { name: "status", type: "string" },
        { name: "farm_id", type: "string", isOptional: true },
        { name: "farm_name", type: "string", isOptional: true },
        { name: "comment", type: "string", isOptional: true },
        { name: "media_type", type: "string", isOptional: true },
        { name: "media_local_uri", type: "string", isOptional: true },
        { name: "media_url", type: "string", isOptional: true },
        { name: "media_metadata_json", type: "string", isOptional: true },
        { name: "sync_status", type: "string" },
        { name: "sync_error", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "application_pyrolysis_links",
      columns: [
        { name: "application_entry_id", type: "string", isIndexed: true },
        { name: "pyrolysis_batch_server_id", type: "string", isIndexed: true },
        { name: "pyrolysis_batch_local_id", type: "string", isOptional: true },
        { name: "kontikki_code", type: "string", isOptional: true },
        { name: "batch_number", type: "string", isOptional: true },
        { name: "producer_name", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: "encrypted_batches",
      columns: [
        { name: "kiln_id", type: "string", isIndexed: true },
        { name: "kontikki_id", type: "string", isOptional: true, isIndexed: true },
        { name: "payload_base64", type: "string" },
        { name: "source_filename", type: "string", isIndexed: true },
        { name: "is_synced", type: "boolean", isIndexed: true },
        { name: "created_at", type: "number" },
      ],
    }),
  ],
});
