// Plain SQLite DDL replacing the WatermelonDB schema/migrations. Fresh start:
// this creates the final (v11-equivalent) shape directly, no historical replay.
export const SCHEMA_VERSION = 6;

export const SCHEMA_STATEMENTS: string[] = [
  `CREATE TABLE IF NOT EXISTS farmers (
    id TEXT PRIMARY KEY NOT NULL,
    server_id TEXT,
    farmer_code TEXT,
    farmer_name TEXT NOT NULL,
    father_spouse_name TEXT,
    agri_id TEXT,
    mobile_number TEXT NOT NULL,
    latitude REAL NOT NULL,
    longitude REAL NOT NULL,
    address TEXT NOT NULL,
    village TEXT,
    mandal TEXT,
    district TEXT,
    state TEXT,
    cluster_id TEXT,
    cluster_village_id TEXT,
    cluster_name TEXT,
    total_land_size REAL NOT NULL,
    owned_land_size REAL,
    leased_land_size REAL,
    farmer_photo_uri TEXT,
    farmer_photo_url TEXT,
    crops TEXT NOT NULL,
    interested_in_biochar INTEGER NOT NULL,
    prior_biochar_exp INTEGER NOT NULL,
    prior_biochar_acreage REAL,
    estimated_biomass REAL NOT NULL,
    created_by TEXT NOT NULL,
    assigned_to TEXT NOT NULL,
    sync_status TEXT NOT NULL,
    sync_error TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  );`,

  `CREATE TABLE IF NOT EXISTS cluster_villages (
    id TEXT PRIMARY KEY NOT NULL,
    cluster_id TEXT NOT NULL,
    cluster_name TEXT NOT NULL,
    village_name TEXT NOT NULL,
    mandal TEXT,
    district TEXT,
    state TEXT,
    updated_at INTEGER NOT NULL
  );`,
  `CREATE INDEX IF NOT EXISTS idx_cluster_villages_cluster_id ON cluster_villages(cluster_id);`,

  `CREATE TABLE IF NOT EXISTS farm_fields (
    id TEXT PRIMARY KEY NOT NULL,
    farmer_id TEXT NOT NULL,
    field_code TEXT NOT NULL,
    ownership_type TEXT NOT NULL,
    land_reference TEXT,
    lease_start TEXT,
    lease_end TEXT,
    status TEXT NOT NULL,
    latitude REAL,
    longitude REAL,
    boundary_geojson TEXT,
    calculated_area REAL,
    water_source TEXT,
    photos_json TEXT NOT NULL,
    notes TEXT,
    crop_name TEXT,
    season TEXT,
    sowing_date TEXT,
    harvest_date TEXT,
    crop_photos_json TEXT,
    server_id TEXT,
    sync_status TEXT,
    sync_error TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  );`,
  `CREATE INDEX IF NOT EXISTS idx_farm_fields_farmer_id ON farm_fields(farmer_id);`,

  `CREATE TABLE IF NOT EXISTS farm_crops (
    id TEXT PRIMARY KEY NOT NULL,
    field_id TEXT NOT NULL,
    farmer_id TEXT NOT NULL,
    crop_code TEXT NOT NULL,
    crop_name TEXT NOT NULL,
    cultivated_area REAL NOT NULL,
    season TEXT,
    ownership_type TEXT,
    photos_json TEXT NOT NULL,
    sowing_date TEXT,
    harvest_date TEXT,
    biomass_rate REAL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  );`,
  `CREATE INDEX IF NOT EXISTS idx_farm_crops_field_id ON farm_crops(field_id);`,
  `CREATE INDEX IF NOT EXISTS idx_farm_crops_farmer_id ON farm_crops(farmer_id);`,

  `CREATE TABLE IF NOT EXISTS farmer_consents (
    id TEXT PRIMARY KEY NOT NULL,
    farmer_id TEXT NOT NULL,
    field_id TEXT,
    agreement_type TEXT NOT NULL,
    consent_status TEXT NOT NULL,
    consent_date TEXT NOT NULL,
    valid_from TEXT,
    valid_to TEXT,
    agreement_reference TEXT,
    document_uri TEXT,
    photos_json TEXT,
    evidence_notes TEXT,
    server_id TEXT,
    sync_status TEXT,
    sync_error TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  );`,
  `CREATE INDEX IF NOT EXISTS idx_farmer_consents_farmer_id ON farmer_consents(farmer_id);`,

  `CREATE TABLE IF NOT EXISTS soil_tests (
    id TEXT PRIMARY KEY NOT NULL,
    farmer_id TEXT NOT NULL,
    field_id TEXT,
    field_ids_json TEXT,
    crop_id TEXT,
    sample_date TEXT NOT NULL,
    sample_lat REAL,
    sample_lng REAL,
    sample_location TEXT,
    sample_photo_uri TEXT,
    sample_photo_url TEXT,
    sample_sites_json TEXT,
    receive_photo_uri TEXT,
    receive_photo_url TEXT,
    lab_source TEXT,
    parameters_json TEXT,
    results_json TEXT,
    notes TEXT,
    submitted_to_supervisor_id TEXT,
    submitted_to_supervisor_name TEXT,
    collected_by TEXT,
    collected_by_role TEXT,
    status TEXT,
    received_at TEXT,
    received_by TEXT,
    received_by_name TEXT,
    server_id TEXT,
    sync_status TEXT,
    sync_error TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  );`,
  `CREATE INDEX IF NOT EXISTS idx_soil_tests_farmer_id ON soil_tests(farmer_id);`,
  `CREATE INDEX IF NOT EXISTS idx_soil_tests_field_id ON soil_tests(field_id);`,

  `CREATE TABLE IF NOT EXISTS soil_reports (
    id TEXT PRIMARY KEY NOT NULL,
    farmer_id TEXT NOT NULL,
    field_id TEXT,
    soil_test_id TEXT,
    report_date TEXT NOT NULL,
    source TEXT,
    results_summary TEXT,
    document_uri TEXT,
    document_url TEXT,
    server_id TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  );`,
  `CREATE INDEX IF NOT EXISTS idx_soil_reports_farmer_id ON soil_reports(farmer_id);`,

  `CREATE TABLE IF NOT EXISTS sync_queue (
    id TEXT PRIMARY KEY NOT NULL,
    entity_type TEXT NOT NULL,
    entity_local_id TEXT NOT NULL,
    operation TEXT NOT NULL,
    status TEXT NOT NULL,
    retries INTEGER NOT NULL,
    error_message TEXT,
    created_at INTEGER NOT NULL
  );`,
  `CREATE INDEX IF NOT EXISTS idx_sync_queue_entity_local_id ON sync_queue(entity_local_id);`,
  `CREATE INDEX IF NOT EXISTS idx_sync_queue_status ON sync_queue(status);`,

  `CREATE TABLE IF NOT EXISTS pyrolysis_sessions (
    id TEXT PRIMARY KEY NOT NULL,
    server_id TEXT,
    operator_id TEXT NOT NULL,
    status TEXT NOT NULL,
    current_step TEXT NOT NULL,
    sync_status TEXT NOT NULL,
    sync_error TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  );`,

  `CREATE TABLE IF NOT EXISTS pyrolysis_batches (
    id TEXT PRIMARY KEY NOT NULL,
    session_id TEXT NOT NULL,
    server_id TEXT,
    kontikki_id TEXT NOT NULL,
    kontikki_code TEXT NOT NULL,
    producer_name TEXT,
    batch_number TEXT,
    feedstock_quantity REAL,
    avg_feedstock_size_cm REAL,
    feedstock_id TEXT,
    feedstock_name TEXT,
    location_lat REAL,
    location_lng REAL,
    location_address TEXT,
    feedstock_photo_local_uri TEXT,
    feedstock_photo_url TEXT,
    feedstock_size_photo_local_uri TEXT,
    feedstock_size_photo_url TEXT,
    feedstock_photo_metadata_json TEXT,
    feedstock_size_photo_metadata_json TEXT,
    moisture_reading_1 REAL,
    moisture_reading_2 REAL,
    moisture_reading_3 REAL,
    moisture_reading_4 REAL,
    moisture_reading_5 REAL,
    moisture_photo_local_uri_1 TEXT,
    moisture_photo_local_uri_2 TEXT,
    moisture_photo_local_uri_3 TEXT,
    moisture_photo_local_uri_4 TEXT,
    moisture_photo_local_uri_5 TEXT,
    moisture_photo_url_1 TEXT,
    moisture_photo_url_2 TEXT,
    moisture_photo_url_3 TEXT,
    moisture_photo_url_4 TEXT,
    moisture_photo_url_5 TEXT,
    moisture_photo_metadata_json_1 TEXT,
    moisture_photo_metadata_json_2 TEXT,
    moisture_photo_metadata_json_3 TEXT,
    moisture_photo_metadata_json_4 TEXT,
    moisture_photo_metadata_json_5 TEXT,
    stage_initial_photo_local_uri TEXT,
    stage_middle_photo_local_uri TEXT,
    stage_final_photo_local_uri TEXT,
    stage_quenching_photo_local_uri TEXT,
    stage_initial_photo_url TEXT,
    stage_middle_photo_url TEXT,
    stage_final_photo_url TEXT,
    stage_quenching_photo_url TEXT,
    stage_initial_captured_at TEXT,
    stage_middle_captured_at TEXT,
    stage_final_captured_at TEXT,
    stage_quenching_captured_at TEXT,
    stage_initial_saved_at TEXT,
    stage_middle_saved_at TEXT,
    stage_final_saved_at TEXT,
    stage_quenching_saved_at TEXT,
    stage_initial_photo_metadata_json TEXT,
    stage_middle_photo_metadata_json TEXT,
    stage_final_photo_metadata_json TEXT,
    stage_quenching_photo_metadata_json TEXT,
    info_completed INTEGER NOT NULL,
    moisture_completed INTEGER NOT NULL,
    pyrolysis_completed INTEGER NOT NULL,
    info_saved_at TEXT,
    moisture_saved_at TEXT,
    pyrolysis_saved_at TEXT,
    yield_saved_at TEXT,
    yield_percent REAL,
    comment TEXT,
    sample_id TEXT,
    sample_photo_local_uri TEXT,
    sample_photo_url TEXT,
    sample_photo_metadata_json TEXT,
    sample_saved_at TEXT,
    sample_completed INTEGER NOT NULL,
    review_status TEXT,
    reviewer_notes TEXT,
    submission_status TEXT NOT NULL DEFAULT 'draft',
    sync_status TEXT NOT NULL,
    sync_error TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  );`,
  `CREATE INDEX IF NOT EXISTS idx_pyrolysis_batches_session_id ON pyrolysis_batches(session_id);`,
  `CREATE INDEX IF NOT EXISTS idx_pyrolysis_batches_kontikki_id ON pyrolysis_batches(kontikki_id);`,

  `CREATE TABLE IF NOT EXISTS mixing_entries (
    id TEXT PRIMARY KEY NOT NULL,
    server_id TEXT,
    operator_id TEXT NOT NULL,
    started_at TEXT NOT NULL,
    status TEXT NOT NULL,
    farm_id TEXT,
    farm_name TEXT,
    location_lat REAL,
    location_lng REAL,
    location_address TEXT,
    material_type TEXT,
    material_to_biochar_ratio REAL,
    comment TEXT,
    biochar_photo_local_uri TEXT,
    biochar_photo_url TEXT,
    biochar_photo_metadata_json TEXT,
    substrate_photo_local_uri TEXT,
    substrate_photo_url TEXT,
    substrate_photo_metadata_json TEXT,
    mixing_photo_local_uri TEXT,
    mixing_photo_url TEXT,
    mixing_photo_metadata_json TEXT,
    review_status TEXT,
    reviewer_notes TEXT,
    sync_status TEXT NOT NULL,
    sync_error TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  );`,
  `CREATE INDEX IF NOT EXISTS idx_mixing_entries_operator_id ON mixing_entries(operator_id);`,

  `CREATE TABLE IF NOT EXISTS mixing_pyrolysis_links (
    id TEXT PRIMARY KEY NOT NULL,
    mixing_entry_id TEXT NOT NULL,
    pyrolysis_batch_server_id TEXT NOT NULL,
    pyrolysis_batch_local_id TEXT,
    kontikki_code TEXT,
    batch_number TEXT,
    producer_name TEXT
  );`,
  `CREATE INDEX IF NOT EXISTS idx_mixing_links_entry_id ON mixing_pyrolysis_links(mixing_entry_id);`,
  `CREATE INDEX IF NOT EXISTS idx_mixing_links_batch_server_id ON mixing_pyrolysis_links(pyrolysis_batch_server_id);`,

  `CREATE TABLE IF NOT EXISTS application_entries (
    id TEXT PRIMARY KEY NOT NULL,
    server_id TEXT,
    operator_id TEXT NOT NULL,
    applied_at TEXT NOT NULL,
    status TEXT NOT NULL,
    farm_id TEXT,
    farm_name TEXT,
    location_lat REAL,
    location_lng REAL,
    location_address TEXT,
    comment TEXT,
    media_type TEXT,
    media_local_uri TEXT,
    media_url TEXT,
    media_metadata_json TEXT,
    review_status TEXT,
    reviewer_notes TEXT,
    sync_status TEXT NOT NULL,
    sync_error TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  );`,
  `CREATE INDEX IF NOT EXISTS idx_application_entries_operator_id ON application_entries(operator_id);`,

  `CREATE TABLE IF NOT EXISTS application_pyrolysis_links (
    id TEXT PRIMARY KEY NOT NULL,
    application_entry_id TEXT NOT NULL,
    pyrolysis_batch_server_id TEXT NOT NULL,
    pyrolysis_batch_local_id TEXT,
    kontikki_code TEXT,
    batch_number TEXT,
    producer_name TEXT
  );`,
  `CREATE INDEX IF NOT EXISTS idx_application_links_entry_id ON application_pyrolysis_links(application_entry_id);`,
  `CREATE INDEX IF NOT EXISTS idx_application_links_batch_server_id ON application_pyrolysis_links(pyrolysis_batch_server_id);`,

  `CREATE TABLE IF NOT EXISTS encrypted_batches (
    id TEXT PRIMARY KEY NOT NULL,
    kiln_id TEXT NOT NULL,
    kontikki_id TEXT,
    payload_base64 TEXT NOT NULL,
    source_filename TEXT NOT NULL,
    is_synced INTEGER NOT NULL,
    created_at INTEGER NOT NULL
  );`,
  `CREATE INDEX IF NOT EXISTS idx_encrypted_batches_kiln_id ON encrypted_batches(kiln_id);`,
  `CREATE INDEX IF NOT EXISTS idx_encrypted_batches_kontikki_id ON encrypted_batches(kontikki_id);`,
  `CREATE INDEX IF NOT EXISTS idx_encrypted_batches_source_filename ON encrypted_batches(source_filename);`,
  `CREATE INDEX IF NOT EXISTS idx_encrypted_batches_is_synced ON encrypted_batches(is_synced);`,
];
